### ISSUE TITLE
Compiler problems on Linux

### ISSUE THREAD

**Issue by dirk-zimoch** [nugatritter/ExtendedObjectOpen62541#1]
g++ does not know the Windows-only functions `printf_s` and `memcpy_s`.
Also, `floor` is not declared because `math.h` is not included.

I also get "undeclared" errors for `UA_STATUSCODE_BAD` and  `UA_STATUSCODE_UNCERTAIN`. Probably a missing open62541 header.

**Comment by dirk-zimoch** [comment]
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by dirk-zimoch** [comment]
I did `#include <cmath>` for `floor()` and replaced all `*_s()` functions with their "normal" counter parts.
I still have the undeclared `UA_STATUSCODE_BAD` and `UA_STATUSCODE_UNCERTAIN` which I cannot find in the open62541 headers either. There are many specific codes  `UA_STATUSCODE_BADsomething` but no "generic" one.

**Comment by nugatritter** [comment]
At Windows there is `open62541\build\src_generated\open62541\statuscodes.h` with `#define UA_STATUSCODE_UNCERTAIN 0x40000000`

**Comment by dirk-zimoch** [comment]
Maybe I need to update. I am at commit c0298a9a6bfcc20cadaf54af640d82cabadfb64e at the moment.

**Comment by nugatritter** [comment]
Next version of the lib `ExtendedObjectOpen62541` won't use this status code anymore. So you can test the current lib by adding `#define UA_STATUSCODE_UNCERTAIN 0x40000000` to header file.

**Comment by dirk-zimoch** [comment]
I have updated open62541 and could compile with the following commandline:
```
c++ -std=c++11 -Wall -I /usr/include/libxml2 -I ../open62541/include -I ../open62541/build/src_generated -I ../open62541/arch -Wl,-rpath,../open62541/build/bin/ -l open62541 -l xml2 ExtendedObjectOpen62541.cpp -o ExtendedObjectOpen62541
```

A Makefile could be helpful....

I see the following warnings:
```
TailQueue.h:154:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
TailQueue.h:160:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
ExtendedObjectOpen62541.cpp:363:23: warning: variable ‘value’ set but not used [-Wunused-but-set-variable]
ExtendedObjectOpen62541.cpp:364:23: warning: variable ‘switchValue’ set but not used [-Wunused-but-set-variable]
ExtendedObjectOpen62541.cpp:454:35: warning: unused variable ‘target’ [-Wunused-variable]
ExtendedObjectOpen62541.cpp:938:90: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
ExtendedObjectOpen62541.cpp:848:22: warning: ‘UA_StatusCode printNodeId(UA_PrintContext*, const UA_NodeId*, const UA_DataType*)’ defined but not used [-Wunused-function]
ExtendedObjectOpen62541.cpp:875:22: warning: ‘UA_StatusCode printByteString(UA_PrintContext*, const UA_ByteString*, const UA_DataType*)’ defined but not used [-Wunused-function]
```

**Comment by dirk-zimoch** [comment]
*_s functions may be in some C++11 standard but my g++ does not have it, even with -std=c++11. Too old maybe.

**Comment by nugatritter** [comment]
Okay, I'll remove them.
